config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats do
    resources :bookings
  end
  resources :planets, only: [:show]  do
    collection do
      get 'mars'


    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flat
  belongs_to :user

  validates :start_time,
  presence: true,
  date: { after: Proc.new { Date.today }, before: :end_time, message: 'must be after today' },
  on: :create

  validates :end_time,
  presence: true,
  date: { after: :start_time, message: 'must be after your start date' }
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :user
  belongs_to :planet
  has_many :bookings, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true, length: { minimum: 3 }
  # validates :planet, presence: true, inclusion: { in: %w(Mars Mercury Moon Venus Earth Jupiter Saturn Uranus Neptune),
  #   message: "%{value} is not a valid planet" }
  validates :capacity, presence: true, numericality: { only_integer: true }
  validates :description, presence: true, length: { minimum: 3 }
  validates :photo, presence: true
end

app/models/planet.rb
class Planet < ApplicationRecord
  has_many :flats
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_many :flats, dependent: :destroy
   has_many :bookings, dependent: :destroy

    validates :email, confirmation: true, presence: true
    validates :first_name, presence: true, length: { minimum: 4 }
    validates :last_name, presence: true, length: { minimum: 4 }
    validates :phone_number, presence: true, numericality: { only_integer: true }
    # validates :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!, only: [:index,:new,:create,:edit,:update,:destroy]
  def index
    @bookings = current_user.bookings
  end

  def show
    find_booking
  end

  def new
    @flat = Flat.find(params[:flat_id])
    @booking = Booking.new
  end

  def create
    @flat = Flat.find(params[:flat_id])
    @booking = Booking.new(booking_params)
    @booking.user_id = current_user.id
    @booking.flat = Flat.find(params[:flat_id])
    if @booking.save
      redirect_to flat_booking_path(flat_id:@booking.flat.id, id:@booking.id)
       # flat_booking GET    /flats/:flat_id/bookings/:id(.:format)
      #index reservation
    else
      render :new
    end
  end

  def edit
    find_booking
  end

  def update
    find_booking
    @booking.update(booking_params)
  end

  def destroy
    find_booking
    @booking.destroy
    redirect_to flats_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_time, :end_time)
  end

  def find_booking
    @booking = Booking.find(params[:id])
  end

end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :authenticate_user!, only: [:new,:create,:edit,:update,:destroy]
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats  = Flat.all
  end

  def show
    @booking = Booking.new
  end

  def new
    @flat =Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.photo.attach(io: params[:flat][:photo], filename: "photo.jpg", content_type: "image/jpg")
    @flat.user = current_user
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    if @flat.update(flat_params)
      redirect_to flat_path(@flat)
    else
      render :edit
    end
  end

  def destroy
    if @flat.user_id == current_user.id
      @flat.destroy
      redirect_to flats_path
    else
      render :show
    end
  end

  def mars
    @flats = Flat.where(planet: flat.planet)
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :planet_id, :capacity, :description, :price)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  def show
    @planet = Planet.find(params[:id])
    @flats = @planet.flats
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # def index
  # end

  # def show
  # end

  # def new
  # end

  # def create
  # end

  # def edit
  # end

  # def update
  # end

  # def destroy
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for([flat, booking]) do |f| %>
  <%= f.input :start_time %>
  <%= f.input :end_time %>
  <%= f.button :submit %>
<% end %>

app/views/bookings/index.html.erb
<div class="d-flex justify-content-between">
  <div></div>
  <h2 class="m-3">Bookings of  <%= current_user.first_name %>  <%= current_user.last_name %> </h2>
  <div></div>
</div>

  <!-- add the cloudanary img -->

<div class="container d-flex justify-content-center">
  <div class="card w-75 bg-dark">
  <% @bookings.each do |booking| %>
    <div class="mb-1">
    <%= cl_image_tag booking.flat.photo.key, height: 200, crop: :fill, class: "card-img-top border_img" %>
    <p class="card_text pl-2">The flat "<%= link_to booking.flat.name, flat_path(booking.flat) %>" is booked from  <%= booking.start_time %> to <%= booking.end_time%>.</p>
    <p><%= link_to "Cancel Reservation", flat_booking_path(flat_id:booking.flat.id, id:booking.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-dark ml-2"  %></p>
    </div>
  <% end %>
  </div>
</div>


<%= link_to "Back home", flats_path, class: "btn btn-dark mb-4 m-3"  %>
<!--


 <h1>flats I rent to someone </h1> -->

app/views/bookings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 offset-sm-2">
      <%= simple_form_for [@flat, @booking] do |f| %>
        <%= f.input :start_time %>
        <%= f.input :end_time %>

        <%= f.submit "Make a booking", class: "btn btn-dark" %>
      <% end %>
      <br><br>
      <%= link_to "Back home", flats_path, class: "btn btn-dark" %>
    </div>
  </div>
</div>


  <!-- create_table "bookings", force: :cascade do |t|
    t.bigint "flat_id"
    t.bigint "user_id"
    t.date "start_time"
    t.date "end_time"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["flat_id"], name: "index_bookings_on_flat_id"
    t.index ["user_id"], name: "index_bookings_on_user_id"
 -->

app/views/bookings/show.html.erb
<div class="container d-flex justify-content-center">
  <div class="card w-75 m-4">
    <%= cl_image_tag @booking.flat.photo.key, height: 200, crop: :fill, class: "card-img-top border_img" %>
    <!-- add the cloudanary img -->
    <div class="card-body p-3">
      <h5 class="card-title">You booked the flat "<%= @booking.flat.name %>"! </h5>
      <p class="card-text">Congratulations! You have booked your own space apartment from <%= @booking[:start_time] %> to <%= @booking[:end_time] %>.</p>
    </div>
  </div>
</div>
<div class="d-flex justify-content-center" >
  <%= link_to "Cancel reservation", flat_booking_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-dark m-2"  %>
  <!-- /flats/:flat_id/bookings/:id(.:format) -->

  <%= link_to "View all my reservations", flat_bookings_path, class: "btn btn-dark m-2"  %>

  <%= link_to "Back home", flats_path, class: "btn btn-dark m-2" %>
</div>

app/views/flats/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 offset-sm-2">
      <%= simple_form_for [@flat] do |f| %>
      <%= f.association :planet  %>
      <%= f.input :name %>
      <%= f.input :capacity %>
      <%= f.input :description%>
      <%= f.input :price %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Update the flat", class: "btn btn-dark" %>
      <%= link_to "Cancel", flats_path, class: "btn btn-dark" %>
      <% end %>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<body class="background-mars">
  <div class="container">
    <%= link_to "Add a flat", new_flat_path, class: "btn btn-dark" %>
    <div class="row">
      <div class="col">
        <h1 class="big-text-planet">
          La planète rouge
        </h1>
        <p class="little-text-planet">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed urna consequat turpis id eget a eget. Et mauris pulvinar dictum metus sapien.</p>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <div class="grid-container">
          <% @flats.each do |flat| %>
          <div class="grid-item">
            <%= link_to flat_path(flat) do %>
            <div class="card" style="margin-left: auto; margin-right: auto; margin-top: 24px;">
              <%= cl_image_tag flat.photo.key, width: 320, height: 260, crop: :fill, class: "card-img-top border_img" %>
              <div class="card-body">
                <p class="card-top-text"><%= flat.planet %></p>
                <h5 class="card-title"><%= flat.name %></h5>
                <p class="card_price"><%= flat.price %>$/night</p>
              </div>
            </div>
            <% end %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</body>

app/views/flats/localisation.html.erb
<div class="d-flex">
<div class="row" id="box-search">
  <div class="thumbnail text-center">
    <%= image_tag "mars_bg.png", alt: "alttext", :class => "img" %>
    <div class="caption">
      <h1 class="big-text-planet">
        La planète rouge
      </h1>
      <p class="little-text-planet">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed urna consequat turpis id eget a eget. Et mauris pulvinar dictum metus sapien.</p>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm">
      <div class="card" style="width: 20rem; margin-left: auto; margin-right: auto; margin-top: 24px;">
        <%= image_tag "mars1.png", alt: "alttext", class: "card-img-top border_img"%>
        <!-- <img class="card-img-top border_img" src="https://source.unsplash.com/random/200x100" alt="Card image cap"> -->
        <div class="card-body">
          <p class="card-top-text">Entire house</p>
          <h5 class="card-title">Card title</h5>
          <p class="card_price">360$/night</p>
        </div>
      </div>
    </div>
    <div class="col-sm">
      <div class="card" style="width: 20rem; margin-left: auto; margin-right: auto; margin-top: 24px;">
        <%= image_tag "mars2.png", alt: "alttext", class: "card-img-top border_img"%>
        <!-- <img class="card-img-top border_img" src="https://source.unsplash.com/random/200x100" alt="Card image cap"> -->
        <div class="card-body">
          <p class="card-top-text">Entire house</p>
          <h5 class="card-title">Card title</h5>
          <p class="card_price">360$/night</p>
        </div>
      </div>
    </div>
    <div class="col-sm">
      <div class="card" style="width: 20rem; margin-left: auto; margin-right: auto; margin-top: 24px;">
        <%= image_tag "mars3.png", alt: "alttext", class: "card-img-top border_img"%>
        <!-- <img class="card-img-top border_img" src="https://source.unsplash.com/random/200x100" alt="Card image cap"> -->
        <div class="card-body">
          <p class="card-top-text">Entire house</p>
          <h5 class="card-title">Card title</h5>
          <p class="card_price">360$/night</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/flats/mars.html.erb
<body class="background-mars">
  <div class="container">
    <div class="row">
      <div class="col">
        <h1 class="big-text-planet">Mars</h1>
        <p class="little-text-planet">C’est une planète tellurique, comme le sont Mercure, Vénus et la Terre,
        environ dix fois moins massive que la Terre mais dix fois plus massive que la Lune. Sa topographie
      présente des analogies aussi bien avec la Lune, à travers ses cratères et ses bassins d'impact, qu'avec
    la Terre, avec des formations d'origine tectonique et climatique telles que des volcans, des rifts, des vallées,
  des mesas, des champs de dunes et des calottes polaires. </p>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <div class="grid-container">
          <% @flats.each do |flat| %>
          <div class="grid-item">
            <%= link_to flat_path(flat) do %>
            <div class="card" style="margin-left: auto; margin-right: auto; margin-top: 24px;">
              <%= cl_image_tag flat.photo.key, width: 320, height: 260, crop: :fill, class: "card-img-top border_img" %>
              <div class="card-body">
                <p class="card-top-text"><%= flat.planet %></p>
                <h5 class="card-title"><%= flat.name %></h5>
                <p class="card_price"><%= flat.price %>$/night</p>
              </div>
            </div>
            <% end %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</body>





<% @flats.each do |flat| %>
<div class="grid-item">
  <%= link_to flat_path(flat) do %>
  <div class="card" style="margin-left: auto; margin-right: auto; margin-top: 24px;">
    <%= cl_image_tag flat.photo.key, width: 320, height: 260, crop: :fill, class: "card-img-top border_img" %>
    <div class="card-body">
      <p class="card-top-text"><%= flat.planet.title %></p>
      <h5 class="card-title"><%= flat.name %></h5>
      <p class="card_price"><%= flat.price %>$/night</p>
    </div>
  </div>
  <% end %>
</div>
<% end %>

app/views/flats/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 offset-sm-2">
      <%= simple_form_for [@flat] do |f| %>
      <%= f.association :planet  %>
      <%= f.input :name %>
      <%= f.input :capacity %>
      <%= f.input :description%>
      <%= f.input :price %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Add a flat", class: "btn btn-dark" %>
      <%= link_to "Cancel", flats_path, class: "btn btn-dark" %>
      <% end %>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<!-- Image -->
<div>
  <%= cl_image_tag @flat.photo.key, crop: :fill, class: "flatcard-image" %>
</div>

<div class="">
  <%= link_to "Update flat", edit_flat_path, class: "btn btn-dark m-1"  %>
  <%= link_to "Delete flat", flat_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-dark m-1"  %>
  <%= link_to "View your bookings", flat_bookings_path(@flat), class: "btn btn-dark m-1"  %>
</div>
<!-- Description and Form -->
<div class="d-flex justify-content-around align-items-center">
  <div class="col-md-6">
    <div class="flatcard-container mt-4 mb-1 ml-4">
      <div class="flatcard">
        <h1><%= @flat[:name] %></h1>
        <p class="flatcard-description"><%= @flat[:description] %></p>
        <p class="flatcard-description"> We have space for: <%= @flat[:capacity] %> people</p>
        <p class="flatcard-description"><%= @flat[:price].to_i %> $</p>
      </div>
    </div>
  </div>

  <div class="col-md-6">
    <div class="container">
      <div class="row d-flex align-items-center h-200">
        <div class="flatcard d-flex justify-content-center align-items-right">
          <%= render 'bookings/form', flat: @flat, booking: @booking %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>SPAACE</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<body class="background">
  <div class="container">
    <div class="row">
        <h1 class="big_title text-left">Find a place to stay in space</h1>
        <p class="texte text-left">Come and live an exceptional experience by staying in one of our apartments in space. Start your experience now and book your own flat.</p>
        <%= link_to 'Find a flat', flats_path, class: "cta_home" %>
      <!-- <div class="background_blur"></div> -->

      <!-- ICON CAROUSEL -->
      <div class="my-5 text-center container background_blur" id="grandcarousel">
        <div class="row d-flex align-items-center">
          <div class="col-1 d-flex align-items-center justify-content-center">
          <a href="#carouselExampleIndicators" role="button" data-slide="prev">
            <div class="carousel-nav-icon">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 129 129" xmlns:xlink="http://www.w3.org/1999/xlink">
              <path d="m88.6,121.3c0.8,0.8 1.8,1.2 2.9,1.2s2.1-0.4 2.9-1.2c1.6-1.6 1.6-4.2 0-5.8l-51-51 51-51c1.6-1.6 1.6-4.2 0-5.8s-4.2-1.6-5.8,0l-54,53.9c-1.6,1.6-1.6,4.2 0,5.8l54,53.9z"/>
              </svg>
            </div>
          </a>
        </div>
        <!-- CAROUSEL -->
        <div class="col-10">
        <!--Start carousel-->
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <div class="row">
                <%= link_to planet_path(Planet.find_by(title: "Mars")) do %>
                <%= image_tag "Mars.png", alt: "alttext", :class => "col-12 col-md d-flex align-items-center justify-content-center"%>
                <% end %>
                <%= link_to planet_path(Planet.find_by(title: "Moon")) do  %>
                <%= image_tag "Lune.png", alt: "alttext", :class => "col-12 col-md d-flex align-items-center justify-content-center" %>
                <% end %>
                <%= link_to planet_path(Planet.find_by(title: "Moon")) do  %>
                <%= image_tag "Venus.png", alt: "alttext", :class => "col-12 col-md d-flex align-items-center justify-content-center" %>
                <% end %>
              </div>
            </div>
            <div class="carousel-item">
              <div class="row">
                <%= link_to planet_path(Planet.find_by(title: "Mars")) do %>
                <%= image_tag "Saturn.png", alt: "alttext", :class => "col-12 col-md d-flex align-items-center justify-content-center"%>
                <% end %>
                <%= link_to planet_path(Planet.find_by(title: "Moon")) do  %>
                <%= image_tag "Neptune.png", alt: "alttext", :class => "col-12 col-md d-flex align-items-center justify-content-center" %>
                <% end %>
                <%= link_to planet_path(Planet.find_by(title: "Moon")) do  %>
                <%= image_tag "Jupiter.png", alt: "alttext", :class => "col-12 col-md d-flex align-items-center justify-content-center" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <!-- ICON CAROUSEL -->
      </div>
      <div class="col-1 d-flex align-items-center justify-content-center"><a  href="#carouselExampleIndicators" data-slide="next">
        <div class="carousel-nav-icon">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 129 129" xmlns:xlink="http://www.w3.org/1999/xlink">
          <path d="m40.4,121.3c-0.8,0.8-1.8,1.2-2.9,1.2s-2.1-0.4-2.9-1.2c-1.6-1.6-1.6-4.2 0-5.8l51-51-51-51c-1.6-1.6-1.6-4.2 0-5.8 1.6-1.6 4.2-1.6 5.8,0l53.9,53.9c1.6,1.6 1.6,4.2 0,5.8l-53.9,53.9z"/>
          </svg>
        </div>
      </a>
    </div>
  </div>
</div>

</div>
</div>
</body>

app/views/planets/show.html.erb
<body class="<%= @planet.title == "Mars" ? 'background-mars' : 'background-moon' %>">
  <div class="container">
    <div class="row">
      <div class="col">
        <h1 class="big-text-planet"><%= @planet.title %></h1>
        <p class="little-text-planet"><%= @planet.description %> </p>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <div class="grid-container">
         <% @flats.each do |flat| %>
         <div class="grid-item">
          <%= link_to flat_path(flat) do %>
          <div class="card" style="margin-left: auto; margin-right: auto; margin-top: 24px;">
            <%= cl_image_tag flat.photo.key, width: 320, height: 260, crop: :fill, class: "card-img-top border_img" %>
            <div class="card-body">
              <p class="card-top-text"><%= flat.planet.title %></p>
              <h5 class="card-title"><%= flat.name %></h5>
              <p class="card_price"><%= flat.price %>$/night</p>
            </div>
          </div>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>
</body>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Add a flat", new_flat_path, class: "btn btn-dark" %>
        </li>
         <li class="nav-item">
          <%= link_to "My reservations", flat_bookings_path(:flat_id,@booking), class: "btn btn-dark" %>
           <!-- /flats/:flat_id/bookings(.:format) -->
        </li>

        <li class="nav-item dropdown">
          <%= image_tag "https://www.angenieux.com/wp-content/uploads/2017/03/Cosmonaute-Lune-Copie.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>